services:
  app:
    image: my-go-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - PORT=8080
    depends_on:
      - db
    networks:
      - my-network

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: local_my
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    networks:
      - my-network
    volumes:
      - pg_data:/var/lib/postgresql/data

networks:
  my-network:
    driver: bridge

volumes:
  pg_data:
