name: Build and Tag Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.0'

      - name: Read version from version.txt
        id: get_version
        run: |
          VERSION=$(cat version.txt)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/my-go-app:${{ env.VERSION }} .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/my-go-app:${{ env.VERSION }}

      - name: Print Docker image version
        run: |
          echo "Docker image version: ghcr.io/${{ github.repository_owner }}/my-go-app:${{ env.VERSION }}"
